image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      sudo apt update -y
      sudo apt install -y libcurl4-openssl-dev libssl-dev libxml2-dev
      sudo apt install -y r-base r-base-dev
      
tasks:
  - command: Rscript requirements.R

vscode:
  extensions:
    - Ikuyadeu.r
